#!/bin/bash

#===========#
#   MySQL   #
#===========#
export MYSQL_HOST=${MYSQL_HOST:-127.0.0.1}
export MYSQL_PORT=${MYSQL_PORT:-3306}
export MYSQL_DB=${MYSQL_DB:-umami}
export MYSQL_USER=${MYSQL_USER:-root}
export MYSQL_PASSWORD=${MYSQL_PASSWORD:-pass4Umami}

# ======================#
# Persistence directory #
#=======================#
export PHP_PERSISTENCE_LIST=(
"/data/php/log"
"/data/php/session"
"/data/zentao")

#==========================================#
# Persistence directory and make soft link #
#==========================================#
export PERSISTENCE_LINK_LIST=(
)
