#!/bin/bash

# shellcheck disable=SC1091

set -o errexit
set -o nounset
set -o pipefail

[ -n "${DEBUG:+1}" ] && set -x

# Load libraries
#. /opt/easysoft/scripts/liblog.sh
. /opt/easysoft/scripts/libmysql.sh
. /opt/easysoft/scripts/libfs.sh

# Load Global/Environment variables
. /etc/s6/s6-init/envs

#======================#
# Check MySQL service  #
#======================#
# Check and waiting mysql to be ready
wait_for_mysql || exit 1

