version: '2'

networks:
  net:
    driver: bridge

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-umami
    ports:
      - '3306:3306'
    volumes:
      - '/data/mysql:/var/lib/mysql'
    environment:
      - MYSQL_DATABASE=umami
      - MYSQL_USER=umami
      - MYSQL_PASSWORD=pass4Umami
      - MYSQL_ROOT_PASSWORD=uQu3Iet9biep8ahgaiz6Aex1
    networks:
      - net
    restart: always

  umami:
    image: hub.qucheng.com/app/umami:${TAG}
    container_name: umami
    ports:
      - '8000:3000'
    volumes:
      - 'data:/data'
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DB=umami
      - MYSQL_USER=umami
      - MYSQL_PASSWORD=pass4Umami
      - DATABASE_TYPE=mysql
    networks:
      - net
    restart: always

# persistence
volumes:
  db:
    driver: local
  data:
    driver: local
