version: '2'

networks:
  net:
    driver: bridge

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - 'db:/var/lib/mysql'
    environment:
      - MYSQL_DB=umami
      - MYSQL_USER=umami
      - MYSQL_PASSWORD=pass4Umami
      - MYSQL_ROOT_PASSWORD=pass4Umami
    networks:
      - net
    restart: always

  umami:
    image: hub.qucheng.com/app/umami:${TAG}
    container_name: umami
    ports:
      - '8000:3000'
    volumes:
      - 'data:/data'
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: umami
      MYSQL_USER: umami
      MYSQL_PASSWORD: pass4Umami
      DATABASE_TYPE: mysql
      DATABASE_URL: mysql://$MYSQL_USER:$MYSQL_PASSWORD@$MYSQL_HOST:3306/$MYSQL_DB
    networks:
      - net
    restart: always

# persistence
volumes:
  db:
    driver: local
  data:
    driver: local
