#!/bin/sh
# yarn common for Dockerfile.

set -e
set -u

# set npm registry by location.
MIRROR=${MIRROR:-false}

if [ "$MIRROR" = "true" ];then
    #npm config set registry http://mirrors.cloud.tencent.com/npm/ # Tencent
    npm config set registry http://registry.npmmirror.com # Ali
    #npm config set registry  https://repo.huaweicloud.com/repository/npm/ # HuaWei
    alias yarn_cmd='yarn --verbose --registry https://registry.npmmirror.com'
else
    alias yarn_cmd='yarn '
fi

yarn_cmd "$@"
