#!/bin/sh
set -e
set -u

# change repo url
if [ "$MIRROR" = "true" ];then
    sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
fi

n=0
max=2
until [ $n -gt $max ]; do
    set +e
    (
      apk add --no-cache "$@"
    )
    CODE=$?
    set -e
    if [ $CODE -eq 0 ]; then
        break
    fi
    if [ $n -eq $max ]; then
        exit $CODE
    fi
    echo "apt failed, retrying"
    n=$(($n + 1))
done
